services:

  api-gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    volumes:
      - ./api_gateway/app:/usr/src/app/app

  user-service:
    build: ./user_service
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
      - SECRET_KEY=your-secret-key-change-this-in-production
    depends_on:
      - db
    volumes:
      - ./user_service/app:/usr/src/app/app

  nutrition-service:
    build: ./nutrition_service
    ports:
      - "8002:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
      - SECRET_KEY=your-secret-key-change-this-in-production
    depends_on:
      - db
    volumes:
      - ./nutrition_service/app:/usr/src/app/app

  logging-analytics-service:
    build: ./logging_analytics_service
    ports:
      - "8003:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/mydatabase
    depends_on:
      - db
    volumes:
      - ./logging_analytics_service/app:/usr/src/app/app

  food-recognition-service:
    build: ./food_recognition_service
    ports:
      - "8004:8000"
    volumes:
      - ./food_recognition_service/app:/usr/src/app/app

  frontend:
    build: ./frontend
    ports:
      - "3000:80" # localhost:3000 maps to container port 80 (Nginx serving React)
    depends_on:
      - api-gateway # optional, if your frontend calls the API gateway
    volumes:
      - ./frontend:/usr/src/app # optional for live development

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5433:5432"

volumes:
  postgres_data:
