"""Add role field to users table

Revision ID: 3f2f928d3536
Revises: 83b876fa6ff3
Create Date: 2025-12-14 18:49:42.355862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3f2f928d3536'
down_revision: Union[str, Sequence[str], None] = '83b876fa6ff3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add role column with default value for existing users
    roleenum = sa.Enum('admin', 'user', name='roleenum')
    roleenum.create(op.get_bind(), checkfirst=True)

    op.add_column('users', sa.Column('role', roleenum, nullable=True, default='user'))

    # Update existing users to have 'user' role
    op.execute("UPDATE users SET role = 'user' WHERE role IS NULL")

    # Make the column NOT NULL
    op.alter_column('users', 'role', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the role column and enum type
    op.drop_column('users', 'role')

    # Drop the enum type
    roleenum = sa.Enum('admin', 'user', name='roleenum')
    roleenum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
